version: "3.6"

services:
  ticker:
    build:
      context: .
    ports:
    - "65010:8080"
    environment:
      TICKER_HOST: database
      TICKER_PORT: 5432      
  database:
    image: postgres:14.5
    environment:
      POSTGRES_PASSWORD: P@ssw0rd
    volumes:
    - "./db/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql"
  flyway:
    build:
      context: .
      dockerfile: db/Dockerfile

networks:
  default:
    name: projectset
    external: true
